M48
; DRILL file KiCad 10.0.3 date 2026-05-26T11:20:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-26T11:20:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
%
G90
G05
T2
X107.58Y-107.08
T1
G00X114.87Y-107.08
M15
G01X115.29Y-107.08
M16
G05
M30
